name: remove label
on:
  pull_request_target:
    types: [synchronize]
jobs:
  remove_label:
    runs-on: ubuntu-latest
    name: remove label
    steps:
      - name: removelabel
        uses: buildsville/add-remove-label@v2.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: Tested
          type: remove
      - name: Post address
        uses: actions/github-script@v6
        if: ${{ success() && github.event_name == 'pull_request_target' }}
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "This pull-request was previously marked with the label Tested, but has been modified with new commits. That label has been removed."
            });
