name: remove label
on:
  pull_request_target:
    types: [synchronize]
jobs:
  remove_label:
    runs-on: ubuntu-latest
    name: remove label
    steps:
      - name: removelabel
        uses: buildsville/add-remove-label@v2.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: Tested
          type: remove
