  name: List workflow last run
  on: workflow_dispatch
  env:
    GH_TOKEN: ${{ github.token }}
  jobs:
    list_workflow:
      runs-on: ubuntu-latest
      outputs:
        messages: ${{ steps.cat_output.outputs }}
      steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: run script
          run: |
            chmod +x ./Scripts/developer_scripts/list_cgal_workflows_last_run.sh
            ./Scripts/developer_scripts/list_cgal_workflows_last_run.sh > output.md
        - name: convert markdown to html
          run: |
            sudo apt-get update && sudo apt-get install -y pandoc
            pandoc -f markdown -t html -o output.html output.md
        - name: tmp
          id: cat_output
          run: cat output.html
    call_send_email:
      needs: list_workflow
      uses: ./.github/workflows/send_email.yml
      with:
        message: ${{needs.list_workflow.outputs.messages}}
      secrets:
        email: ${{ secrets.CGAL_SEND_WIKI_EMAIL_TO }}
        private_key: ${{ secrets.CGAL_SEND_WIKI_EMAIL_SSH_PRIVATE_KEY }}
        user: ${{ secrets.CGAL_SEND_WIKI_EMAIL_SSH_USER }}
        host: ${{ secrets.CGAL_SEND_WIKI_EMAIL_SSH_HOST }}
