  name: List workflow last run
  on: workflow_dispatch
  env:
    GH_TOKEN: ${{ github.token }}
  jobs:
    list_workflow:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: run script
          run: |
            chmod +x ./Scripts/developer_scripts/list_cgal_workflows_last_run.sh
            ./Scripts/developer_scripts/list_cgal_workflows_last_run.sh > output.md
    call_send_email:
      needs: list_workflow
      uses: ./.github/workflows/send_email.yml
      with:
        message: $(cat output.md)
      secrets:
        email: ${{ secrets.CGAL_SEND_WIKI_EMAIL_TO }}
        private_key: ${{ secrets.CGAL_SEND_WIKI_EMAIL_SSH_PRIVATE_KEY }}
        user: ${{ secrets.CGAL_SEND_WIKI_EMAIL_SSH_USER }}
        host: ${{ secrets.CGAL_SEND_WIKI_EMAIL_SSH_HOST }}
