  name: List workflow last run
  on: workflow_dispatch
  jobs:
    list_workflow:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: run script
          run: ./Scripts/developer_scripts/list_cgal_workflows_last_run.sh
