name: Emoji on Comment

on: issue_comment

jobs:
  emoji:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/emoji-helper@v1.0.0
        with:
          type: 'comment'
          emoji: '+1, laugh, heart, hooray, rocket, eyes'
