on:
  issue_comment:

jobs:
  emoji:
    runs-on: ubuntu-latest
    steps:
      - name: emoji-comment
        uses: actions-cool/emoji-helper@v1.0.0
        with:
          type: 'comment'
          emoji: 'rocket'
          comment-id: ${{ github.event.comment.id }}
