on:
  pull_request_target:

jobs:
  emoji:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/emoji-helper@v1.0.0
        with:
          type: 'pr'
          emoji: '+1, laugh, heart, hooray, rocket, eyes'
