on:
  issue_comment:

jobs:
  emoji:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: 4
          body-includes: /build:v0
      - name: emoji-comment
        uses: actions-cool/emoji-helper@v1.0.0
        with:
          type: 'comment'
          emoji: 'rocket'
          comment-id: steps.fc.outputs.comment-id
