name: Send Email 

on:
  workflow_call:
    inputs:
      message:
        description: 'Message to send'
        required: true
        type: string
        default: ''
      email:
        description: 'Email address to send to'
        required: true
        type: string
        default: ''
    secrets:
      private_key:
        required: true

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.private_key }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ vars.SSH_HOST }} > ~/.ssh/known_hosts
    - name: send email via ssh
      run: |
        echo "${{ inputs.message }}" | ssh  nsaillant@${{ vars.SSH_HOST }} "/sbin/sendmail -t ${{ inputs.email }}"
