on: issue_comment
jobs:
  test:
    permissions:
      pull-requests: write # to create comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: test
        with:
          script: |
            return 421094206
      - name: getWorkflowId
        id: workflowid
        run: |
          curl "https://api.github.com/repos/SaillantNicolas/cgal-web/actions/artifacts/${{ steps.test.outputs.result }}" -o artifact.json
          echo "::set-output name=id::$(cat artifact.json | jq -r '.workflow_run.id')"
      - name: githuboutput
        id: testoutput
        run: echo "DoxygenError=No package affected." >> $GITHUB_OUTPUT
      - name: copy
        id: testenv
        run: |
          delimiter="$(openssl rand -hex 8)"
          echo "DoxygenError<<${delimiter}" >> "${GITHUB_OUTPUT}"
          cat artifact.json >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"
          exit 1
      - name: paste
        run: echo "${{ steps.testenv.outputs.DoxygenError}}"

      - name: getPrId
        id: prid
        run: |
          curl "https://api.github.com/repos/SaillantNicolas/cgal-web/actions/runs/${{ steps.workflowid.outputs.id }}" -o workflow.json
          echo "::set-output name=id::$(cat workflow.json | jq -r '.pull_requests[0].id')"
      - run: echo ${{ steps.prid.outputs.id }}
      - name: Post error
        uses: actions/github-script@v6
        if: ${{ failure() && steps.get_round.outputs.result != 'stop' }}
        with:
          script: |
            const error = `"warning: tag INPUT: input source `/home/runner/work/cgal/cgal/Mesh_3/include//CGAL/Detect_features_in_image.h' does not exist
                          warning: tag INPUT: input source `/home/runner/work/cgal/cgal/Mesh_3/include//CGAL/Detect_features_on_image_bbox.h' does not exist
                          warning: source /home/runner/work/cgal/cgal/Mesh_3/include//CGAL/Detect_features_in_image.h is not a readable file or directory... skipping.
                          warning: source /home/runner/work/cgal/cgal/Mesh_3/include//CGAL/Detect_features_on_image_bbox.h is not a readable file or directory... skipping."`
            const msg = "There was an error while building the doc: \n"+error
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.issue.number }},
              body: msg
            });
