on: push

env:
  TEST: 4
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: test
        with:
          script: |
            return 421094206
      - name: getWorkflowId
        id: workflowid
        run: |
          curl "https://api.github.com/repos/SaillantNicolas/cgal-web/actions/artifacts/${{ steps.test.outputs.result }}" -o artifact.json
          echo "::set-output name=id::$(cat artifactid.json | jq -r '.workflow_run.id')"
      - name: getPrId
        id: prid
        run: |
          curl "https://api.github.com/repos/SaillantNicolas/cgal-web/actions/runs/${{ steps.workflowid.outputs.id }}" -o workflow.json
          echo "::set-output name=id::$(cat workflow.json | jq -r '.pull_requests[0].id')"
      - run: echo ${{ steps.prid.outputs.id }}
    
