on: push

env:
  TEST: 4
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: test
        with:
          script: |
            return 421094206
      - name: getWorkflowId
        id: test2
        run: |
          curl "https://api.github.com/repos/SaillantNicolas/cgal-web/actions/artifacts/${{ steps.test.outputs.result }}" | jq -r '.workflow_run.id'
      - run: echo ${{steps.test2.outputs }} 
    
