on: issue_comment
jobs:
  test:
    permissions:
      pull-requests: write # to create comment
    runs-on: ubuntu-latest
    steps:
      - name: copy
        id: testenv
        run: |
          delimiter="$(openssl rand -hex 8)"
          echo "DoxygenError<<${delimiter}" >> "${GITHUB_OUTPUT}"
          echo warning: tag INPUT: input source `/home/runner/work/cgal/cgal/Mesh_3/include//CGAL/Detect_features_in_image.h'' does not exist
                warning: tag INPUT: input source `/home/runner/work/cgal/cgal/Mesh_3/include//CGAL/Detect_features_on_image_bbox.h'' does not exist
                warning: source /home/runner/work/cgal/cgal/Mesh_3/include//CGAL/Detect_features_in_image.h is not a readable file or directory... skipping.
                warning: source /home/runner/work/cgal/cgal/Mesh_3/include//CGAL/Detect_features_on_image_bbox.h is not a readable file or directory... skipping. >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"
          exit 1
      - name: paste
        run: echo "${{ steps.testenv.outputs.DoxygenError}}"
      - name: Post error
        uses: actions/github-script@v6
        if: ${{ failure() && steps.get_round.outputs.result != 'stop' }}
        with:
          script: |
            const error = `${{steps.testenv.outputs.DoxygenError}}``
            const msg = "There was an error while building the doc: \n"+error
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.issue.number }},
              body: msg
            });
