on: push

env:
  TEST: 4
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: test
        with:
          script: |
            return 5
      - run: echo "${{steps.test.outputs.result}}"
    
