name: ssh
on: [push]

jobs:
  ssh:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ls
        run:  ls
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: rsync
        run: rsync -avz ./testrsync.html nsaillant@cgal.geometryfactory.com:/home/nsaillant/public_html
