on: push

env:
  TEST: 4
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            var test = 5
      - run: echo $TEST
    
