name: Gollum Workflow

on: gollum
  
jobs:
  prepare_email:
    runs-on: ubuntu-latest
    outputs:
      messages: ${{ steps.set-result.outputs.result }}
    steps:
    - name: get informations and prepare email
      uses: actions/github-script@v6
      id: set-result
      with:
        result-encoding: string
        script: |
          const payload = context.payload;
          const actor = payload.sender.login;
          const pages = payload.pages;
          let messages = "Subject:Updates to CGAL Wiki \n";
          for (const page of pages){
              messages += `The CGAL Wiki page "${page.title}" was ${page.action} by ${actor}.\n`;
          }
          console.log( messages );
          return messages;
  call_send_email:
    needs: prepare_email
    uses: ./.github/workflows/send_email.yml
    with:
      message: ${{needs.prepare_email.outputs.messages}}
      email: ${{ vars.SEND_EMAIL_TO }}
    secrets:
      private_key: ${{ secrets.CGAL_SEND_EMAIL_SSH_PRIVATE_KEY }}
      user: ${{ secrets.CGAL_SEND_EMAIL_SSH_USER }}
