name: Gollum Workflow

on: [gollum,workflow_dispatch]
  

jobs:
  run_script:
    runs-on: ubuntu-latest
    outputs:
      messages: ${{ steps.set-result.outputs.result }}
    steps:
    - name: get informations and prepare email
      uses: actions/github-script@v6
      id: set-result
      with:
        result-encoding: string
        script: |
          const payload = context.payload;
          const actor = payload.sender.login;
          const pages = payload.pages;
          let messages = "Subject:Wiki Change \n";
          for (const page of pages){
              messages += `Page ${page.title} ${page.action} by ${actor} \n`;
          }
          console.log( messages );
          return messages;
  call_send_email:
    needs: run_script
    uses: SaillantNicolas/testaction/.github/workflows/send_email.yml@main
    with:
      message: ${{needs.run_script.outputs.messages}}
      email: saillantnicolas01@gmail.com
    secrets:
      private_key: ${{ secrets.SSH_PRIVATE_KEY }}
