name: Gollum Workflow

on: [gollum,workflow_dispatch]
  

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: get informations and prepare email
      uses: actions/github-script@v6
      id: set-result
      with:
        result-encoding: string
        script: |
          const payload = context.payload;
          const sender = payload.sender;
          const pages = payload.pages;
          const action = pages.action;
          const title = pages.title;
          const html_url = pages.html_url;
          const message = sender + action + title + html_url;
          return message
    - name: Get result
      run: echo "${{steps.set-result.outputs.result}}"
