name: Gollum Workflow

on: [gollum,workflow_dispatch]
  

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: get informations and prepare email
      uses: actions/github-script@v6
      id: set-result
      with:
        result-encoding: string
        script: |
          const payload = context.payload;
          const actor = payload.sender.login;
          const pages = payload.pages;
          let messages = "";
          for (const page of pages){
              messages += `Page ${payload.pages.title} ${payload.pages.action} by ${actor} \n`;
          }
          console.log( messages );
