name: Gollum Workflow

on: [gollum,workflow_dispatch]
  

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: get informations and prepare email
      uses: actions/github-script@v6
      id: set-result
      with:
        result-encoding: string
        script: |
          const payload = context.payload;
          const sender = payload.sender;
          const pages = payload.pages;
          const message = "";
          #for (const page of pages){
          #    message += `\n ${page.action} + ${page.title} + ${page.html_url}`;
          #  };
          return pages
    - name: Get result
      run: echo "${{steps.set-result.outputs.result}}"
