name: Gollum Workflow

on: gollum

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Connect to Remote Host
      uses: actions/ssh-action@v1
      with:
        host: ${{ vars.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          ssh ${{ secrets.SSH_USER }}@${{ vars.SSH_HOST }} "./your_script.sh"
